"""init

Revision ID: b6c67e0ed2ea
Revises: 
Create Date: 2026-04-20 19:22:22.044836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c67e0ed2ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('records_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('carriers',
    sa.Column('carrier_id', sa.BigInteger(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('inn', sa.String(length=20), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('fleet_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('carrier_id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('weight_mode', sa.String(length=20), nullable=True),
    sa.Column('manual_weights_json', sa.Text(), nullable=True),
    sa.Column('swara_config_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrier_behavior',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carrier_id', sa.BigInteger(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.carrier_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('initiated_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_criteria',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('scenario_id', 'criterion_id')
    )
    op.create_table('shipments',
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('carrier_id', sa.BigInteger(), nullable=True),
    sa.Column('shipper_id', sa.BigInteger(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('destination', sa.Text(), nullable=True),
    sa.Column('pickup_window_start', sa.DateTime(), nullable=True),
    sa.Column('pickup_window_end', sa.DateTime(), nullable=True),
    sa.Column('delivery_window_start', sa.DateTime(), nullable=True),
    sa.Column('delivery_window_end', sa.DateTime(), nullable=True),
    sa.Column('cargo_type', sa.Text(), nullable=True),
    sa.Column('ordered_quantity', sa.Integer(), nullable=True),
    sa.Column('delivered_quantity', sa.Integer(), nullable=True),
    sa.Column('client_rating', sa.Integer(), nullable=True),
    sa.Column('force_majeure', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.carrier_id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_table('claims',
    sa.Column('claim_id', sa.BigInteger(), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('carrier_id', sa.BigInteger(), nullable=True),
    sa.Column('claim_type', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('carrier_fault', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.carrier_id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ),
    sa.PrimaryKeyConstraint('claim_id')
    )
    op.create_table('run_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.BigInteger(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.carrier_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_documents',
    sa.Column('doc_id', sa.BigInteger(), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('carrier_id', sa.BigInteger(), nullable=True),
    sa.Column('doc_type', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('payment_due_date', sa.Date(), nullable=True),
    sa.Column('payment_actual_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.carrier_id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('shipment_events',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('carrier_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('cancelled_by', sa.Text(), nullable=True),
    sa.Column('is_carrier_fault', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.carrier_id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_events')
    op.drop_table('shipment_documents')
    op.drop_table('run_results')
    op.drop_table('claims')
    op.drop_table('shipments')
    op.drop_table('scenario_criteria')
    op.drop_table('runs')
    op.drop_table('carrier_behavior')
    op.drop_table('scenarios')
    op.drop_table('carriers')
    op.drop_table('users')
    op.drop_table('datasets')
    op.drop_table('criteria')
    # ### end Alembic commands ###
